from enum import Enum

BYTE_SIZE = 8
BUTTONS_REPORT_ID = 17
BOARD_REPORT_ID = 16

BUTTON_QUANTITY = 4
SIDE_BUTTON_QUANTITY = 2

BUTTON_OFFSET = 1
DISTANCE_OFFSET = 1
XCOORD_OFFSET = 2
YCOORD_OFFSET = 5
PRESSURE_OFFSET = 8

class Distance(Enum):
    OUT = 0
    FAR = 1
    CLOSE = 2
    TOUCHING = 3